name: glowup_app
description: GlowUp teacher companion demo app skeleton.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  http: ^1.2.0
  url_launcher: ^6.2.5
  video_player: ^2.8.2
  just_audio: ^0.9.36
  audio_session: ^0.1.16
  image: ^4.1.3
  fl_chart: ^0.66.2
  fftea: ^1.0.1
  mime: ^1.0.5
  file_picker: ^8.0.6
  universal_io: ^2.2.2
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
